name: Backend Continuous Integration

on:
  # Manual trigger using the workflow_dispatch event.
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - 'cicd-backend/**'
      - '.github/workflows/backend**'

jobs:
  lint:
    name: Lint Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev
        working-directory: cicd-backend/backend

      - name: Run linting
        run: pipenv run lint
        working-directory: cicd-backend/backend
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev
        working-directory: cicd-backend/backend

      - name: Run tests
        run: pipenv run test
        working-directory: cicd-backend/backend
  build:
    name: Build Job
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application using Docker and push to ECR
        run: docker build --tag mp-backend:latest .
        working-directory: cicd-backend/backend
